using System;

/// <summary>
/// This attribute is here so we can get better Pex integration
/// Using this means that Pex will not try to inspect the work of 
/// the actual proxies being generated by Rhino Mocks
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
[CLSCompliant(false)]
public class __ProtectAttribute : Attribute
{
    
}